Repository ConsenSys/rimble-ui, pull requests merged in 2019-10, with the labels that each got.

#367 fix for select overflow
  src/Select/__snapshots__/Select.test.js.snap
  src/Select/index.js
Labels: bug, ready to merge

#368 Added props and descriptions from QR code and set default props.
  src/QR/index.js
Labels: documentation, ready to merge

#384 Ml add theme breakpoints #383
  src/Flash/__snapshots__/Flash.test.js.snap
  src/MetaMaskButton/__snapshots__/MetaMaskButton.test.js.snap
  src/Select/__snapshots__/Select.test.js.snap
  src/ToastMessage/__snapshots__/ToastMessage.test.js.snap
  src/Tooltip/__snapshots__/Tooltip.test.js.snap
  src/UPortButton/__snapshots__/uportbutton.test.js.snap
  src/theme.js
Labels: enhancement

#385 Upgraded husky hook. Fixes #372.
  package.json
Labels: bug

#386 Update issue template to latest rimble version
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#387 Added default font-size to Heading by as prop
  demo/src/App.js
  src/Heading/Heading.test.js
  src/Heading/__snapshots__/Heading.test.js.snap
  src/Heading/index.js
  storybook/stories/Heading.stories.js
Labels: documentation, enhancement

#377 Fixed warning when building
  rollup.config.js
Labels: bug
