Repository ConsenSys/rimble-ui, pull requests merged in 2019-07, with the labels that each got.

#329 forward refs on all components
  example/package.json
  example/src/App.js
  example/src/stories/Field/field.stories.js
  example/src/stories/Radio/radio.stories.js
  example/src/stories/ToastMessage/toastmessage.stories.js
  example/src/stories/Tooltip/tooltip.stories.js
  example/yarn.lock
  package.json
  src/Avatar/index.js
  src/Box/index.js
  src/Button/BaseButton.js
  src/Button/SolidButton.js
  src/Button/__snapshots__/Button.test.js.snap
  src/Card/__snapshots__/Card.test.js.snap
  src/Card/index.js
  src/Checkbox/__snapshots__/Checkbox.test.js.snap
  src/Checkbox/index.js
  src/Field/Field.test.js
  src/Field/__snapshots__/Field.test.js.snap
  src/Field/index.js
  src/Flash/__snapshots__/Flash.test.js.snap
  src/Flash/index.js
  src/Flex/index.js
  src/Form/__snapshots__/form.test.js.snap
  src/Heading/index.js
  src/Icon/__snapshots__/Icon.test.js.snap
  src/Icon/index.js
  src/Image/__snapshots__/Image.test.js.snap
  src/Image/index.js
  src/Input/__snapshots__/FileInput.test.js.snap
  src/Input/__snapshots__/Input.test.js.snap
  src/Input/index.js
  src/Link/__snapshots__/Link.test.js.snap
  src/Link/index.js
  src/Loader/index.js
  src/MetaMaskButton/__snapshots__/MetaMaskButton.test.js.snap
  src/Pill/__snapshots__/Pill.test.js.snap
  src/Pill/index.js
  src/Progress/index.js
  src/PublicAddress/__snapshots__/PublicAddress.test.js.snap
  src/QR/index.js
  src/Radio/__snapshots__/Radio.test.js.snap
  src/Radio/index.js
  src/Select/__snapshots__/Select.test.js.snap
  src/Select/index.js
  src/Slider/index.js
  src/Table/__snapshots__/Table.test.js.snap
  src/Table/index.js
  src/Text/index.js
  src/Textarea/__snapshots__/Textarea.test.js.snap
  src/Textarea/index.js
  src/ThemeProvider/index.js
  src/ToastMessage/__snapshots__/ToastMessage.test.js.snap
  src/ToastMessage/index.js
  src/Tooltip/Tooltip.test.js
  src/Tooltip/__snapshots__/Tooltip.test.js.snap
  src/Tooltip/index.js
  src/UPortButton/__snapshots__/uportbutton.test.js.snap
  yarn.lock
Labels: enhancement

#331 add props for value and label to Select
  example/src/App.js
  example/src/stories/Select/docs.md
  example/src/stories/Select/select.stories.js
  src/Select/Select.test.js
  src/Select/__snapshots__/Select.test.js.snap
  src/Select/index.js
Labels: enhancement, ready to merge

#334 Force nested Field component inside PublicAddress to full width.
  example/src/stories/PublicAddress/docs.md
  example/src/stories/PublicAddress/publicaddress.stories.js
  src/PublicAddress/index.js
Labels: bug, ready to merge

#332 Added theme prop-type for ThemeProvider.
  src/ThemeProvider/index.js
Labels: documentation, ready to merge

#343 merge 0.9.5 release
  README.md
  example/src/App.js
  example/src/stories/PublicAddress/docs.md
  example/src/stories/PublicAddress/publicaddress.stories.js
  example/src/stories/Select/docs.md
  example/src/stories/Select/select.stories.js
  package.json
  src/PublicAddress/index.js
  src/Select/Select.test.js
  src/Select/__snapshots__/Select.test.js.snap
  src/Select/index.js
  src/ThemeProvider/index.js
  yarn.lock
Labels: ready to merge

#351 Eth Address wordbreak
  src/EthAddress/__snapshots__/EthAddress.test.js.snap
  src/EthAddress/index.js
Labels: ready to merge
